Enhancement of the cron service and use of the SDK library
dojot/cron pull request #49
Opened 2021-09-16 14:15 UTC by gilmaicor

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
*dojot/dojot#2032
*dojot/dojot#2033
*dojot/dojot#2034
*dojot/dojot#2078
*dojot/dojot#2095
*dojot/dojot#2035

* **Other information**:

2021-09-17 12:06 UTC, cfrancisco approved these changes, later dismissed

2021-09-17 13:52 UTC, luissajunior requested changes

2021-09-17 13:52 UTC, luissajunior commented on app/broker.js
> +          return;
Here dont need resolve or reject?

2021-09-20 11:18 UTC, gilmaicor commented on app/broker.js
> +          return;
done

2021-09-20 11:43 UTC, luissajunior approved these changes

2021-09-20 16:03 UTC, cfrancisco approved these changes

2021-09-20 17:01 UTC, merged